### ISSUE TITLE
Python error when launching

### ISSUE THREAD

**Issue by coom** [dangmocrang/check_idrac#53]
Hi,

I would like to use your script to monitor my Dell iDRAC, but when I launch it against any of my host, I get the following errror :

```python
Traceback (most recent call last):
  File "./idrac_2.2rc4", line 848, in <module>
    result, tmp_code = PARSER().main()
  File "./idrac_2.2rc4", line 765, in main
    else: hw_4 = float(hw[4])/10
ValueError: could not convert string to float: (n/a)
```

Did you got an idea to address this please ?

Guillaume T.

**Comment by ChristianMoritz** [comment]
ive got a similar error.

```Traceback (most recent call last):
  File "./idrac_2.2rc4", line 848, in <module>
    result, tmp_code = PARSER().main()
  File "./idrac_2.2rc4", line 644, in main
    hw_dict = self.classifier(snmp_data, hw_dict)  # classify data
  File "./idrac_2.2rc4", line 413, in classifier
    item_order = int(_.split()[0].split('.')[-1])
ValueError: invalid literal for int() with base 10: 'Bad'
```
