### ISSUE TITLE
Error on some hosts

### ISSUE THREAD

**Issue by ChristianMoritz** [dangmocrang/check_idrac#55]
on some dell host's ive got the following error...

Plugin-Ausgabe
PS
--PS 1: OK, Volt I/O: 264 V/228.0 V, Current: 0.8 A, Watt I/O: 900.0 W/750.0 W
--PS 2: OK, Volt I/O: 264 V/228.0 V, Current: 0.2 A, Watt I/O: 900.0 W/750.0 W
FAN
--System Board Fan1: 4560 RPM - ENABLED/OK
--System Board Fan2: 4680 RPM - ENABLED/OK
--System Board Fan3: 4680 RPM - ENABLED/OK
--System Board Fan4: 4560 RPM - ENABLED/OK
--System Board Fan5: 4560 RPM - ENABLED/OK
--System Board Fan6: 4440 RPM - ENABLED/OK
BATTERY
--System Board CMOS Battery: ENABLED/OK [PRESENCEDETECTED]
--PERC1 ROMB Battery: ENABLED/OK [PRESENCEDETECTED]
--PERC2 ROMB Battery: ENABLED/OK [0]
PU
--PU 1: ENABLED/OK, RedundancyStatus: FULL, SystemBoard Pwr Consumption: 196 W
MEM
--Memory 1 (DIMM Socket A1) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 2 (DIMM Socket A2) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 3 (DIMM Socket A3) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 4 (DIMM Socket A4) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 5 (DIMM Socket A5) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 6 (DIMM Socket B1) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 7 (DIMM Socket B2) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 8 (DIMM Socket B3) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 9 (DIMM Socket B4) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 10 (DIMM Socket B5) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 11 (DIMM Socket A7) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 12 (DIMM Socket A8) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 13 (DIMM Socket B7) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
--Memory 14 (DIMM Socket B8) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: YYYYYYYYYYYY]
VDISK
--VDisk 1 (): OK/ONLINE, RAID-1 (136.13 GB), BadBlock: 0 [Virtual Disk 0 on Integrated RAID Controller 1]
DISK
--PDisk 1 (0:1:0) 136.13 GB: ONLINE, PowerStat: SPUNUP, HotSpare: no [TOSHIBA, S/N: YYYYYYYYYYYY]
--PDisk 2 (0:1:1) 136.13 GB: ONLINE, PowerStat: SPUNUP, HotSpare: no [TOSHIBA, S/N: YYYYYYYYYYYY]
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_dell_idrac.py", line 885, in <module>
    result, tmp_code = PARSER(host, hw_info, hw_order, hw_no_alert, hw_mib, perf).main()
  File "/usr/lib/nagios/plugins/check_dell_idrac.py", line 718, in main
    else: hw_3 = round(float(hw[3])/10, 1)
ValueError: could not convert string to float: "CPU1 TEMP"

on 1 other host ive got a timeout.... (like this)

PS
--PS 1: OK, Volt I/O: 264 V/(N/A) V, Current: 0.2 A, Watt I/O: 900.0 W/750.0 W
--PS 2: OK, Volt I/O: 264 V/(N/A) V, Current: 21.0 A, Watt I/O: 900.0 W/750.0 W
FAN
--System Board Fan1: 3000 RPM - ENABLED/OK
--System Board Fan2: 2880 RPM - ENABLED/OK
--System Board Fan3: 3000 RPM - ENABLED/OK
--System Board Fan4: 2880 RPM - ENABLED/OK
--System Board Fan5: 3000 RPM - ENABLED/OK
--System Board Fan6: 3000 RPM - ENABLED/OK
BATTERY
--System Board CMOS Battery: ENABLED/OK [PRESENCEDETECTED]
PU
--PU 1: ENABLED/OK, RedundancyStatus: FULL, SystemBoard Pwr Consumption: 210 W
MEM
--Memory 1 (DIMM Socket A1) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 2 (DIMM Socket A2) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 3 (DIMM Socket A3) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 4 (DIMM Socket A4) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 5 (DIMM Socket A5) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 6 (DIMM Socket A6) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 7 (DIMM Socket A7) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 8 (DIMM Socket A8) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 9 (DIMM Socket B1) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 10 (DIMM Socket B2) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 11 (DIMM Socket B3) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 12 (DIMM Socket B4) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 13 (DIMM Socket B5) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 14 (DIMM Socket B6) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 15 (DIMM Socket B7) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
--Memory 16 (DIMM Socket B8) 32.0 GB/2400 MHz: ENABLED/OK [26, Samsung, S/N: YYYYYYYYYYYY]
VDISK
--VDisk 1 (Volume0): OK/ONLINE, RAID-1 (185.75 GB), BadBlock: 0 [Virtual Disk 0 on Integrated RAID Controller 1]
DISK
--PDisk 1 (0:1:0) 185.75 GB: ONLINE, PowerStat: ON, HotSpare: no [ATA, S/N: YYYYYYYYYYYY]
--PDisk 2 (0:1:1) 185.75 GB: ONLINE, PowerStat: ON, HotSpare: no [ATA, S/N: YYYYYYYYYYYY]
SNMP Timeout!

**Comment by eeshlomi** [comment]
I have applied a bugfix for that. Check-out my [pull request](https://github.com/dangmocrang/check_idrac/pull/56/commits/5b59d999f6c7aef601e4dc7f51beb43c06f89e3a) or the [whole fork](https://github.com/eeshlomi/check_idrac) in my repos.

**Comment by ChristianMoritz** [comment]
> I have applied a bugfix for that. Check-out my [pull request](https://github.com/dangmocrang/check_idrac/pull/56/commits/5b59d999f6c7aef601e4dc7f51beb43c06f89e3a) or the [whole fork](https://github.com/eeshlomi/check_idrac) in my repos.

with your tool fork ive got the following error at the end...

`root@smon03:/usr/lib/nagios/plugins/idrac# ./idrac_2.2rc4 -H 1.1.1.9 -v2c -c SnmPv2c-T3st
PS
--PS 1: OK, Volt I/O: 264 V/228 V, Current: 0.8 A, Watt I/O: 900.0 W/750 W
--PS 2: OK, Volt I/O: 264 V/228 V, Current: 0.2 A, Watt I/O: 900.0 W/750 W
DISK
--PDisk 1 (0:1:0) 136.13 GB: ONLINE, PowerStat: SPUNUP, HotSpare: no [TOSHIBA, HDD, S/N: XXXXXXX] isFailing: 0
--PDisk 2 (0:1:1) 136.13 GB: ONLINE, PowerStat: SPUNUP, HotSpare: no [TOSHIBA, HDD, S/N: XXXXXXX] isFailing: 0
FAN
--System Board Fan2: 4680 RPM - ENABLED/OK
--System Board Fan3: 4680 RPM - ENABLED/OK
--System Board Fan4: 4560 RPM - ENABLED/OK
--System Board Fan5: 4560 RPM - ENABLED/OK
--System Board Fan6: 4440 RPM - ENABLED/OK
--System Board Fan1: 4560 RPM - ENABLED/OK
BATTERY
--System Board CMOS Battery: ENABLED/OK [PRESENCEDETECTED]
--PERC1 ROMB Battery: ENABLED/OK [PRESENCEDETECTED]
--PERC2 ROMB Battery: ENABLED/OK [0]
PU
--PU 1: ENABLED/OK, RedundancyStatus: FULL, SystemBoard Pwr Consumption: 196 W
MEM
--Memory 1 (DIMM Socket A1) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 2 (DIMM Socket A2) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 3 (DIMM Socket A3) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 4 (DIMM Socket A4) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 5 (DIMM Socket A5) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 6 (DIMM Socket B1) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 7 (DIMM Socket B2) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 8 (DIMM Socket B3) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 9 (DIMM Socket B4) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 10 (DIMM Socket B5) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 11 (DIMM Socket A7) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 12 (DIMM Socket A8) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 13 (DIMM Socket B7) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
--Memory 14 (DIMM Socket B8) 32.0 GB/1333 MHz: ENABLED/OK [DDR3, Samsung, S/N: XXXXXXX]
VDISK
--VDisk 1 (): OK/ONLINE, RAID-1 (136.13 GB), BadBlock: 0 [Virtual Disk 0 on Integrated RAID Controller 1]
Traceback (most recent call last):
  File "./idrac_2.2rc4", line 861, in <module>
    result, tmp_code = PARSER().main()
  File "./idrac_2.2rc4", line 648, in main
    hw_dict = self.classifier(snmp_data, hw_dict)  # classify data
  File "./idrac_2.2rc4", line 417, in classifier
    item_order = int(_.split()[0].split('.')[-1])
ValueError: invalid literal for int() with base 10: 'Bad'
root@smon03:/usr/lib/nagios/plugins/idrac#
`

**Comment by eeshlomi** [comment]
Hi Christian,

In the aforementioned line (#417) an integer is expected but a string is provided ('Bad')
To investigate that - and improve the code - please edit the script and uncomment the line right above by removing the preceding "#--", and then run it.
It will fail again with the same error, but will also show the full output so that I can fix the code to interpret it correctly.

Thanks,
E.

**Comment by eeshlomi** [comment]
Fixed: https://github.com/eeshlomi/check_idrac/tree/d93738dc0bcb60f5a1c550153ba0b74160df30dd
More details under issue https://github.com/dangmocrang/check_idrac/issues/58
