### ISSUE TITLE
Getting Below Error Please find the error below

### ISSUE THREAD

**Issue by abdularshad06** [dangmocrang/check_idrac#69]
[admin@nagios check_idrac-master]$ ./idrac_check.py -H Idrac_IP-X.X.X.X -v 3 -u snmp -a sha -A snmp1234 -x aes -X snmp1234 -l noAuthNoPriv -m idrac-smiv2.mib -w MEM
Traceback (most recent call last):
  File "./idrac_check.py", line 896, in <module>
    result, exit_code = PARSER().main()
  File "./idrac_check.py", line 620, in main
    snmp_data = self.get_snmp(oids=self.hardware[0])
  File "./idrac_check.py", line 388, in get_snmp
    scProc = run(snmp_cli.split(' '), capture_output=True)  # query snmp data
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
[admin@nagios check_idrac-master]$

**Comment by Djdodo666** [comment]
I have the same problem.
I already changed the first line to python3.6 as we don't have 3.11

**Comment by robert-scheck** [comment]
This has been fixed with my (merged) pull request #89, please test and update this issue.
